# title: Minimalist theme
title: Dr. Yangjun Zhang
# description: Minimalist is a theme powered by Jekyll. It is modified based on the Minimal theme.
description:  NLPer
show_downloads: false
google_analytics: UA-108144808-1
theme: jekyll-theme-minimalist
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
